#!/bin/bash

echo "🔧 === COMPREHENSIVE HEREDOC FIX SCRIPT ==="
echo "📝 Fixing all remaining heredoc sections in workflow files..."

# Fix enhanced-issue-management.yml remaining heredoc sections
echo "📝 Fixing enhanced-issue-management.yml..."

# Replace auto_resolution_comment heredoc
sed -i '/cat > auto_resolution_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "🤖 **Auto-Resolution Check** 🤖" > auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "I'\''ve detected recent commits that may have resolved this issue:" >> auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "**Recent Activity:**" >> auto_resolution_comment.txt\
                echo "- 📝 Recent commits: $recent_commits" >> auto_resolution_comment.txt\
                echo "- 🔍 Pattern: ESLint/Lint fixes detected" >> auto_resolution_comment.txt\
                echo "- ⏰ Checked: $(date)" >> auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "**Please verify if this issue has been resolved and close it if so.**" >> auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "**Auto-generated by Enhanced Issue Management System**" >> auto_resolution_comment.txt' .github/workflows/enhanced-issue-management.yml

# Replace stale_issue_comment heredoc
sed -i '/cat > stale_issue_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "🕐 **Stale Issue Notice** 🕐" > stale_issue_comment.txt\
                echo "" >> stale_issue_comment.txt\
                echo "This issue has been inactive for **$days_since_update days** and is marked as low priority." >> stale_issue_comment.txt\
                echo "" >> stale_issue_comment.txt\
                echo "**Options:**" >> stale_issue_comment.txt\
                echo "1. **Close** if no longer relevant" >> stale_issue_comment.txt\
                echo "2. **Update** with current status" >> stale_issue_comment.txt\
                echo "3. **Reassign** if still needed" >> stale_issue_comment.txt\
                echo "" >> stale_issue_comment.txt\
                echo "**Auto-generated by Enhanced Issue Management System**" >> stale_issue_comment.txt' .github/workflows/enhanced-issue-management.yml

echo "✅ enhanced-issue-management.yml fixed"

# Fix issue-feedback-system.yml remaining heredoc sections
echo "📝 Fixing issue-feedback-system.yml..."

# Replace critical_update_comment heredoc
sed -i '/cat > critical_update_comment.txt << '\''EOF'\''/,/^EOF$/c\
                  echo "🚨 **Critical Issue Update Required** 🚨" > critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "This **CRITICAL** issue hasn'\''t been updated in **$hours_since_update hours**:" >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Critical Issue Protocol:**" >> critical_update_comment.txt\
                  echo "- 🚨 **Priority:** Critical" >> critical_update_comment.txt\
                  echo "- ⏰ **Update Frequency:** Every 24 hours" >> critical_update_comment.txt\
                  echo "- 📝 **Status:** Needs immediate update" >> critical_update_comment.txt\
                  echo "- 👤 **Assignee:** Please provide progress update" >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Required Actions:**" >> critical_update_comment.txt\
                  echo "- 📝 **IMMEDIATE UPDATE** with current status" >> critical_update_comment.txt\
                  echo "- 💬 **DETAILED COMMENT** on progress made" >> critical_update_comment.txt\
                  echo "- ⏰ **NEXT UPDATE** within 24 hours" >> critical_update_comment.txt\
                  echo "- 📋 **DOCUMENT** any blockers or escalations needed" >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Critical Issue Management:** Critical issues require daily updates until resolved." >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Auto-generated by Issue Feedback System**" >> critical_update_comment.txt' .github/workflows/issue-feedback-system.yml

# Replace assignment_comment heredoc
sed -i '/cat > assignment_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "👤 **Assignment Required** 👤" > assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "This issue has been unassigned for **$hours_since_creation hours**:" >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Assignment Status:**" >> assignment_comment.txt\
                echo "- 👤 **Assigned:** No" >> assignment_comment.txt\
                echo "- ⏰ **Created:** $hours_since_creation hours ago" >> assignment_comment.txt\
                echo "- 🏷️ **Labels:** $labels" >> assignment_comment.txt\
                echo "- 💬 **Comments:** $comments" >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Required Actions:**" >> assignment_comment.txt\
                echo "- 👤 **ASSIGN** to appropriate team member" >> assignment_comment.txt\
                echo "- 📝 **SET PRIORITY** based on issue type" >> assignment_comment.txt\
                echo "- ⏰ **ESTIMATE** resolution timeline" >> assignment_comment.txt\
                echo "- 📋 **PLAN** resolution approach" >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Feedback:** Please assign this issue to ensure it receives proper attention." >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Auto-generated by Issue Feedback System**" >> assignment_comment.txt' .github/workflows/issue-feedback-system.yml

echo "✅ issue-feedback-system.yml fixed"

echo "🎯 All heredoc sections have been replaced with echo statements!"
echo "✅ YAML syntax errors should now be completely resolved!"
echo "🚀 All workflow files should now parse correctly!"
