#!/bin/bash

# Fix all remaining heredoc sections in workflow files

echo "🔧 Fixing all remaining heredoc sections..."

# Fix security-issue-management.yml
echo "📝 Fixing security-issue-management.yml..."

# Replace security_update_comment heredoc
sed -i '/cat > security_update_comment.txt << '\''EOF'\''/,/^EOF$/c\
              echo "🚨 **SECURITY UPDATE REQUIRED** 🚨" > security_update_comment.txt\
              echo "" >> security_update_comment.txt\
              echo "**CRITICAL SECURITY ISSUE UPDATE NEEDED**" >> security_update_comment.txt\
              echo "" >> security_update_comment.txt\
              echo "This critical security issue hasn'\''t been updated in **$hours_since_update hours**:" >> security_update_comment.txt\
              echo "" >> security_update_comment.txt\
              echo "**Required Actions:**" >> security_update_comment.txt\
              echo "- 📝 **UPDATE STATUS** immediately" >> security_update_comment.txt\
              echo "- 🔍 **PROVIDE PROGRESS** on security assessment" >> security_update_comment.txt\
              echo "- 📋 **DOCUMENT ACTIONS** taken" >> security_update_comment.txt\
              echo "- ⏰ **SET NEXT UPDATE** within 2 hours" >> security_update_comment.txt\
              echo "" >> security_update_comment.txt\
              echo "**Security Protocol:** Critical security issues must be updated every 4 hours until resolved." >> security_update_comment.txt\
              echo "" >> security_update_comment.txt\
              echo "**Auto-generated by Critical Security Management System**" >> security_update_comment.txt' .github/workflows/security-issue-management.yml

# Replace high_security_comment heredoc
sed -i '/cat > high_security_comment.txt << '\''EOF'\''/,/^EOF$/c\
              echo "⚠️ **HIGH SECURITY ISSUE** ⚠️" > high_security_comment.txt\
              echo "" >> high_security_comment.txt\
              echo "This is a **HIGH PRIORITY SECURITY ISSUE** that requires prompt attention:" >> high_security_comment.txt\
              echo "" >> high_security_comment.txt\
              echo "**Security Protocol:**" >> high_security_comment.txt\
              echo "- 🔒 **Classification:** High Security" >> high_security_comment.txt\
              echo "- ⏰ **Response Time:** Within 4 hours" >> high_security_comment.txt\
              echo "- 👤 **Assignment:** Should be assigned to security team" >> high_security_comment.txt\
              echo "- 📋 **Documentation:** Actions should be documented" >> high_security_comment.txt\
              echo "" >> high_security_comment.txt\
              echo "**Required Actions:**" >> high_security_comment.txt\
              echo "1. **ASSIGN** to security team member" >> high_security_comment.txt\
              echo "2. **BEGIN ASSESSMENT** within 4 hours" >> high_security_comment.txt\
              echo "3. **DOCUMENT ACTIONS** taken" >> high_security_comment.txt\
              echo "4. **UPDATE PROGRESS** regularly" >> high_security_comment.txt\
              echo "" >> high_security_comment.txt\
              echo "**Auto-generated by Security Management System**" >> high_security_comment.txt' .github/workflows/security-issue-management.yml

# Replace security_reminder_comment heredoc
sed -i '/cat > security_reminder_comment.txt << '\''EOF'\''/,/^EOF$/c\
              echo "⚠️ **SECURITY ISSUE REMINDER** ⚠️" > security_reminder_comment.txt\
              echo "" >> security_reminder_comment.txt\
              echo "This high security issue has been open for **$days_old days**:" >> security_reminder_comment.txt\
              echo "" >> security_reminder_comment.txt\
              echo "**Status Check:**" >> security_reminder_comment.txt\
              echo "- 🔍 **Assessment:** Please provide current status" >> security_reminder_comment.txt\
              echo "- 📝 **Progress:** Document any progress made" >> security_reminder_comment.txt\
              echo "- ⏰ **Timeline:** Update expected resolution time" >> security_reminder_comment.txt\
              echo "- 📋 **Actions:** List actions taken or planned" >> security_reminder_comment.txt\
              echo "" >> security_reminder_comment.txt\
              echo "**Auto-generated by Security Management System**" >> security_reminder_comment.txt' .github/workflows/security-issue-management.yml

# Replace security_resolution_comment heredoc
sed -i '/cat > security_resolution_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "🔍 **Security Resolution Check** 🔍" > security_resolution_comment.txt\
                echo "" >> security_resolution_comment.txt\
                echo "I'\''ve detected recent commits that may have resolved this security issue:" >> security_resolution_comment.txt\
                echo "" >> security_resolution_comment.txt\
                echo "**Recent Security Activity:**" >> security_resolution_comment.txt\
                echo "- 📝 Recent commits: $recent_commits" >> security_resolution_comment.txt\
                echo "- 🔍 Pattern: Security fixes detected" >> security_resolution_comment.txt\
                echo "- ⏰ Checked: $(date)" >> security_resolution_comment.txt\
                echo "- 🔒 Security focus: Vulnerability fixes identified" >> security_resolution_comment.txt\
                echo "" >> security_resolution_comment.txt\
                echo "**⚠️ IMPORTANT:** Please verify that this security issue has been properly resolved:" >> security_resolution_comment.txt\
                echo "1. **Test the fix** thoroughly" >> security_resolution_comment.txt\
                echo "2. **Verify security** of the solution" >> security_resolution_comment.txt\
                echo "3. **Document** the resolution" >> security_resolution_comment.txt\
                echo "4. **Close** only after verification" >> security_resolution_comment.txt\
                echo "" >> security_resolution_comment.txt\
                echo "**Security Note:** Security issues require extra verification before closure." >> security_resolution_comment.txt\
                echo "" >> security_resolution_comment.txt\
                echo "**Auto-generated by Security Management System**" >> security_resolution_comment.txt' .github/workflows/security-issue-management.yml

# Replace false_positive_comment heredoc
sed -i '/cat > false_positive_comment.txt << '\''EOF'\''/,/^EOF$/c\
              echo "🔍 **False Positive Review** 🔍" > false_positive_comment.txt\
              echo "" >> false_positive_comment.txt\
              echo "This security issue has been marked as a false positive." >> false_positive_comment.txt\
              echo "" >> false_positive_comment.txt\
              echo "**Review Required:**" >> false_positive_comment.txt\
              echo "- ✅ **Confirm** it'\''s actually a false positive" >> false_positive_comment.txt\
              echo "- 📝 **Document** why it'\''s not a security risk" >> false_positive_comment.txt\
              echo "- 🔒 **Verify** no security implications" >> false_positive_comment.txt\
              echo "- 🗑️ **Close** if confirmed false positive" >> false_positive_comment.txt\
              echo "" >> false_positive_comment.txt\
              echo "**Security Note:** Even false positives should be verified by security team." >> false_positive_comment.txt\
              echo "" >> false_positive_comment.txt\
              echo "**Auto-generated by Security Management System**" >> false_positive_comment.txt' .github/workflows/security-issue-management.yml

echo "✅ security-issue-management.yml fixed"

# Fix enhanced-issue-management.yml
echo "📝 Fixing enhanced-issue-management.yml..."

# Replace escalation_comment heredoc
sed -i '/cat > escalation_comment.txt << '\''EOF'\''/,/^EOF$/c\
              echo "🚨 **ESCALATION NOTICE** 🚨" > escalation_comment.txt\
              echo "" >> escalation_comment.txt\
              echo "This critical issue has been open for **$hours_old hours** and requires immediate resolution." >> escalation_comment.txt\
              echo "" >> escalation_comment.txt\
              echo "**Escalation Actions:**" >> escalation_comment.txt\
              echo "- 🏷️ Added '\''escalated'\'' label" >> escalation_comment.txt\
              echo "- 📢 Notifying team leads" >> escalation_comment.txt\
              echo "- ⏰ Monitoring for resolution" >> escalation_comment.txt\
              echo "" >> escalation_comment.txt\
              echo "**Auto-generated by Enhanced Issue Management System**" >> escalation_comment.txt' .github/workflows/enhanced-issue-management.yml

# Replace security_critical_comment heredoc
sed -i '/cat > security_critical_comment.txt << '\''EOF'\''/,/^EOF$/c\
              echo "🔒 **CRITICAL SECURITY ISSUE** 🔒" > security_critical_comment.txt\
              echo "" >> security_critical_comment.txt\
              echo "This security issue has been flagged as CRITICAL and requires immediate attention:" >> security_critical_comment.txt\
              echo "" >> security_critical_comment.txt\
              echo "**Security Protocol:**" >> security_critical_comment.txt\
              echo "- 🚨 **Priority:** Critical Security" >> security_critical_comment.txt\
              echo "- ⏰ **Response Time:** Immediate" >> security_critical_comment.txt\
              echo "- 🔒 **Confidentiality:** Handle with care" >> security_critical_comment.txt\
              echo "- 📋 **Documentation:** Document all actions taken" >> security_critical_comment.txt\
              echo "" >> security_critical_comment.txt\
              echo "**Required Actions:**" >> security_critical_comment.txt\
              echo "1. Assign to security team member immediately" >> security_critical_comment.txt\
              echo "2. Begin security assessment" >> security_critical_comment.txt\
              echo "3. Document remediation steps" >> security_critical_comment.txt\
              echo "4. Update with progress within 4 hours" >> security_critical_comment.txt\
              echo "" >> security_critical_comment.txt\
              echo "**Auto-generated by Enhanced Security Issue Management**" >> security_critical_comment.txt' .github/workflows/enhanced-issue-management.yml

# Replace auto_resolution_comment heredoc
sed -i '/cat > auto_resolution_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "🤖 **Auto-Resolution Check** 🤖" > auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "I'\''ve detected recent commits that may have resolved this issue:" >> auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "**Recent Activity:**" >> auto_resolution_comment.txt\
                echo "- 📝 Recent commits: $recent_commits" >> auto_resolution_comment.txt\
                echo "- 🔍 Pattern: ESLint/Lint fixes detected" >> auto_resolution_comment.txt\
                echo "- ⏰ Checked: $(date)" >> auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "**Please verify if this issue has been resolved and close it if so.**" >> auto_resolution_comment.txt\
                echo "" >> auto_resolution_comment.txt\
                echo "**Auto-generated by Enhanced Issue Management System**" >> auto_resolution_comment.txt' .github/workflows/enhanced-issue-management.yml

# Replace stale_issue_comment heredoc
sed -i '/cat > stale_issue_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "🕐 **Stale Issue Notice** 🕐" > stale_issue_comment.txt\
                echo "" >> stale_issue_comment.txt\
                echo "This issue has been inactive for **$days_since_update days** and is marked as low priority." >> stale_issue_comment.txt\
                echo "" >> stale_issue_comment.txt\
                echo "**Options:**" >> stale_issue_comment.txt\
                echo "1. **Close** if no longer relevant" >> stale_issue_comment.txt\
                echo "2. **Update** with current status" >> stale_issue_comment.txt\
                echo "3. **Reassign** if still needed" >> stale_issue_comment.txt\
                echo "" >> stale_issue_comment.txt\
                echo "**Auto-generated by Enhanced Issue Management System**" >> stale_issue_comment.txt' .github/workflows/enhanced-issue-management.yml

echo "✅ enhanced-issue-management.yml fixed"

# Fix issue-feedback-system.yml
echo "📝 Fixing issue-feedback-system.yml..."

# Replace critical_update_comment heredoc
sed -i '/cat > critical_update_comment.txt << '\''EOF'\''/,/^EOF$/c\
                  echo "🚨 **Critical Issue Update Required** 🚨" > critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "This **CRITICAL** issue hasn'\''t been updated in **$hours_since_update hours**:" >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Critical Issue Protocol:**" >> critical_update_comment.txt\
                  echo "- 🚨 **Priority:** Critical" >> critical_update_comment.txt\
                  echo "- ⏰ **Update Frequency:** Every 24 hours" >> critical_update_comment.txt\
                  echo "- 📝 **Status:** Needs immediate update" >> critical_update_comment.txt\
                  echo "- 👤 **Assignee:** Please provide progress update" >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Required Actions:**" >> critical_update_comment.txt\
                  echo "- 📝 **IMMEDIATE UPDATE** with current status" >> critical_update_comment.txt\
                  echo "- 💬 **DETAILED COMMENT** on progress made" >> critical_update_comment.txt\
                  echo "- ⏰ **NEXT UPDATE** within 24 hours" >> critical_update_comment.txt\
                  echo "- 📋 **DOCUMENT** any blockers or escalations needed" >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Critical Issue Management:** Critical issues require daily updates until resolved." >> critical_update_comment.txt\
                  echo "" >> critical_update_comment.txt\
                  echo "**Auto-generated by Issue Feedback System**" >> critical_update_comment.txt' .github/workflows/issue-feedback-system.yml

# Replace assignment_comment heredoc
sed -i '/cat > assignment_comment.txt << '\''EOF'\''/,/^EOF$/c\
                echo "👤 **Assignment Required** 👤" > assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "This issue has been unassigned for **$hours_since_creation hours**:" >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Assignment Status:**" >> assignment_comment.txt\
                echo "- 👤 **Assigned:** No" >> assignment_comment.txt\
                echo "- ⏰ **Created:** $hours_since_creation hours ago" >> assignment_comment.txt\
                echo "- 🏷️ **Labels:** $labels" >> assignment_comment.txt\
                echo "- 💬 **Comments:** $comments" >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Required Actions:**" >> assignment_comment.txt\
                echo "- 👤 **ASSIGN** to appropriate team member" >> assignment_comment.txt\
                echo "- 📝 **SET PRIORITY** based on issue type" >> assignment_comment.txt\
                echo "- ⏰ **ESTIMATE** resolution timeline" >> assignment_comment.txt\
                echo "- 📋 **PLAN** resolution approach" >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Feedback:** Please assign this issue to ensure it receives proper attention." >> assignment_comment.txt\
                echo "" >> assignment_comment.txt\
                echo "**Auto-generated by Issue Feedback System**" >> assignment_comment.txt' .github/workflows/issue-feedback-system.yml

echo "✅ issue-feedback-system.yml fixed"

echo "🎯 All heredoc sections have been replaced with echo statements!"
echo "✅ YAML syntax errors should now be resolved!"
