# Testing Site Configuration
# Comprehensive testing configuration for automated validation

# Test Categories
test_categories:
  security:
    name: "Security Testing"
    description: "Security validation and vulnerability scanning"
    tests:
      - name: "Security Headers"
        type: "static"
        command: "grep -q 'Content-Security-Policy' index.html"
        required: true
      - name: "XSS Protection"
        type: "static"
        command: "grep -q 'X-XSS-Protection' index.html"
        required: true
      - name: "Frame Options"
        type: "static"
        command: "grep -q 'X-Frame-Options' index.html"
        required: true
      - name: "Content Type Options"
        type: "static"
        command: "grep -q 'X-Content-Type-Options' index.html"
        required: true

  accessibility:
    name: "Accessibility Testing"
    description: "WCAG 2.1 AA compliance validation"
    tests:
      - name: "WCAG 2.1 AA Compliance"
        type: "pa11y"
        command: "pa11y --standard WCAG2AA index.html"
        required: true
      - name: "Keyboard Navigation"
        type: "static"
        command: "grep -q 'tabindex' index.html"
        required: false
      - name: "Alt Text"
        type: "static"
        command: "grep -q 'alt=' index.html"
        required: true
      - name: "ARIA Labels"
        type: "static"
        command: "grep -q 'aria-label' index.html"
        required: false

  performance:
    name: "Performance Testing"
    description: "Core Web Vitals and performance optimization"
    tests:
      - name: "Lighthouse Performance"
        type: "lighthouse"
        command: "lighthouse index.html --output=json --chrome-flags='--headless'"
        required: true
      - name: "Image Optimization"
        type: "static"
        command: "find . -name '*.jpg' -o -name '*.png' | head -5"
        required: false
      - name: "CSS Optimization"
        type: "static"
        command: "grep -q 'media' testing-styles.css"
        required: true
      - name: "JavaScript Optimization"
        type: "static"
        command: "grep -q 'testingEnvironment' testing-script.js"
        required: true

  seo:
    name: "SEO Optimization"
    description: "Search engine optimization validation"
    tests:
      - name: "Meta Description"
        type: "static"
        command: "grep -q 'meta name=\"description\"' index.html"
        required: true
      - name: "Meta Keywords"
        type: "static"
        command: "grep -q 'meta name=\"keywords\"' index.html"
        required: true
      - name: "Title Tag"
        type: "static"
        command: "grep -q 'title>' index.html"
        required: true
      - name: "Structured Data"
        type: "static"
        command: "grep -q 'application/ld+json' index.html"
        required: false

  mobile:
    name: "Mobile Responsiveness"
    description: "Mobile device compatibility validation"
    tests:
      - name: "Viewport Meta Tag"
        type: "static"
        command: "grep -q 'viewport' index.html"
        required: true
      - name: "Responsive CSS"
        type: "static"
        command: "grep -q 'media' testing-styles.css"
        required: true
      - name: "Touch Targets"
        type: "static"
        command: "grep -q 'min-height: 44px' testing-styles.css"
        required: false
      - name: "Mobile Navigation"
        type: "static"
        command: "grep -q 'hamburger' index.html"
        required: true

  cost_optimization:
    name: "Cost Optimization"
    description: "Cost management and optimization validation"
    tests:
      - name: "Cost Monitoring Script"
        type: "file"
        command: "test -f cost-monitor.sh"
        required: true
      - name: "Cleanup Script"
        type: "file"
        command: "test -f cleanup-testing.sh"
        required: true
      - name: "Deployment Script"
        type: "file"
        command: "test -f deploy-testing.sh"
        required: true
      - name: "Budget Configuration"
        type: "static"
        command: "grep -q 'BUDGET_LIMIT' cost-monitor.sh"
        required: true

  code_quality:
    name: "Code Quality"
    description: "Code quality and maintainability validation"
    tests:
      - name: "HTML Validation"
        type: "html-validate"
        command: "html-validate index.html features.html"
        required: true
      - name: "CSS Validation"
        type: "static"
        command: "grep -q 'media' testing-styles.css"
        required: true
      - name: "JavaScript Quality"
        type: "static"
        command: "grep -q 'function' testing-script.js"
        required: true
      - name: "File Structure"
        type: "file"
        command: "test -f README.md"
        required: true

# Test Execution Configuration
execution:
  parallel: false
  timeout: 300
  retries: 2
  fail_fast: false

# Reporting Configuration
reporting:
  format: "markdown"
  output: "test-report.md"
  include_details: true
  include_recommendations: true

# Thresholds
thresholds:
  pass_rate: 90
  critical_failures: 0
  warning_threshold: 5

# Notifications
notifications:
  on_success: true
  on_failure: true
  on_warning: true
  email: "your-email@example.com"

# Environment Configuration
environment:
  node_version: "18"
  tools:
    - "lighthouse"
    - "pa11y"
    - "html-validate"
    - "snyk"
  browsers:
    - "chrome"
    - "firefox"
    - "safari"

# Cost Monitoring
cost_monitoring:
  budget_limit: 10.00
  alert_threshold: 8.00
  services:
    - "s3"
    - "cloudfront"
    - "route53"
  tags:
    - "Environment:testing"
    - "Purpose:private-testing"

# Security Configuration
security:
  headers:
    - "Content-Security-Policy"
    - "X-Content-Type-Options"
    - "X-Frame-Options"
    - "X-XSS-Protection"
    - "Referrer-Policy"
  vulnerabilities:
    - "xss"
    - "csrf"
    - "injection"
    - "clickjacking"
  scanning:
    - "dependency"
    - "static"
    - "dynamic"

# Performance Configuration
performance:
  metrics:
    - "lcp"
    - "fid"
    - "cls"
    - "fcp"
    - "ttfb"
  thresholds:
    lcp: 2.5
    fid: 100
    cls: 0.1
    fcp: 1.8
    ttfb: 600
  optimization:
    - "compression"
    - "minification"
    - "caching"
    - "lazy-loading"

# Accessibility Configuration
accessibility:
  standards:
    - "WCAG2AA"
    - "WCAG2AAA"
  checks:
    - "color-contrast"
    - "keyboard-navigation"
    - "screen-reader"
    - "focus-management"
  tools:
    - "pa11y"
    - "axe"
    - "lighthouse"

# SEO Configuration
seo:
  meta_tags:
    - "title"
    - "description"
    - "keywords"
    - "viewport"
  structured_data:
    - "json-ld"
    - "microdata"
    - "rdfa"
  technical:
    - "sitemap"
    - "robots.txt"
    - "canonical"
    - "hreflang"
