name: License Compliance Check

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging" ]
  schedule:
    # Run license check weekly on Sundays at 3:00 UTC
    - cron: '0 3 * * 0'

jobs:
  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install license checker
      run: npm install -g license-checker

    - name: Check JavaScript dependencies licenses
      run: |
        echo "🔍 Checking JavaScript dependencies licenses..."
        if [ -f "package.json" ]; then
          npm install
          license-checker --onlyAllow "MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;Unlicense;CC0-1.0;Python-2.0;BSD-3-Clause-Clear;0BSD" --excludePrivatePackages --json > license-report.json
          echo "✅ License check completed"
        else
          echo "ℹ️ No package.json found, skipping JavaScript license check"
          echo "{}" > license-report.json
        fi

    - name: Check for GPL licenses (blocking)
      run: |
        echo "🚨 Checking for GPL licenses (blocking)..."
        if [ -f "license-report.json" ]; then
          if grep -q -E "GPL-[0-9]|GPLv[0-9]|GNU General Public License" license-report.json; then
            echo "❌ GPL licenses detected - blocking deployment"
            exit 1
          else
            echo "✅ No GPL licenses found"
          fi
        fi

    - name: Check for AGPL licenses (blocking)
      run: |
        echo "🚨 Checking for AGPL licenses (blocking)..."
        if [ -f "license-report.json" ]; then
          if grep -q -E "AGPL-[0-9]|AGPLv[0-9]|GNU Affero General Public License" license-report.json; then
            echo "❌ AGPL licenses detected - blocking deployment"
            exit 1
          else
            echo "✅ No AGPL licenses found"
          fi
        fi

    - name: Check for Copyleft licenses (warning)
      run: |
        echo "⚠️ Checking for Copyleft licenses (warning)..."
        if [ -f "license-report.json" ]; then
          if grep -q "LGPL\|MPL\|EPL\|CDDL" license-report.json; then
            echo "⚠️ Copyleft licenses detected - review required"
            cat license-report.json | grep -E "LGPL|MPL|EPL|CDDL"
          else
            echo "✅ No Copyleft licenses found"
          fi
        fi

    - name: Generate license summary
      run: |
        echo "📋 License Summary:"
        if [ -f "license-report.json" ]; then
          echo "Total dependencies: $(cat license-report.json | jq 'length')"
          echo "License distribution:"
          cat license-report.json | jq -r '.[] | .licenses' | sort | uniq -c | sort -nr
        fi

    - name: Upload license report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: license-compliance-report
        path: license-report.json
        retention-days: 30

  # Check for license headers in source files
  source-license-check:
    name: Source License Header Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check for license headers in JavaScript files
      run: |
        echo "🔍 Checking for license headers in JavaScript files..."
        missing_headers=0
        for file in $(find . -name "*.js" -not -path "./node_modules/*" -not -path "./.git/*"); do
          if ! head -10 "$file" | grep -q "Copyright\|License\|MIT\|Apache"; then
            echo "⚠️ Missing license header in: $file"
            missing_headers=$((missing_headers + 1))
          fi
        done
        
        if [ $missing_headers -gt 0 ]; then
          echo "⚠️ $missing_headers JavaScript files missing license headers"
        else
          echo "✅ All JavaScript files have license headers"
        fi

    - name: Check for license headers in Python files
      run: |
        echo "🔍 Checking for license headers in Python files..."
        missing_headers=0
        for file in $(find . -name "*.py" -not -path "./node_modules/*" -not -path "./.git/*"); do
          if ! head -10 "$file" | grep -q "Copyright\|License\|MIT\|Apache"; then
            echo "⚠️ Missing license header in: $file"
            missing_headers=$((missing_headers + 1))
          fi
        done
        
        if [ $missing_headers -gt 0 ]; then
          echo "⚠️ $missing_headers Python files missing license headers"
        else
          echo "✅ All Python files have license headers"
        fi

    - name: Check for license headers in Terraform files
      run: |
        echo "🔍 Checking for license headers in Terraform files..."
        missing_headers=0
        for file in $(find terraform/ -name "*.tf" -not -path "./.git/*"); do
          if ! head -10 "$file" | grep -q "Copyright\|License\|MIT\|Apache"; then
            echo "⚠️ Missing license header in: $file"
            missing_headers=$((missing_headers + 1))
          fi
        done
        
        if [ $missing_headers -gt 0 ]; then
          echo "⚠️ $missing_headers Terraform files missing license headers"
        else
          echo "✅ All Terraform files have license headers"
        fi
